### PR TITLE
Add travis CI support

### PR DESCRIPTION
**Pull request by wangmengyan95**

### CODE REVIEW

**Comment by grantland** [comment]
Have you done the rest of the set up? It doesn't seem to have run on this PR.

**Comment by wangmengyan95** [comment]
@grantland , I do not have permission to add this project to travis, could you help me to add it?

**Comment by grantland** [comment]
it's now on

**Comment by wangmengyan95** [comment]
@grantland It works, although horribly slow..

**Comment by grantland** [comment]
Looks great!

**Pull request merged**
